language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

env: DB=mysql

jdk: oraclejdk7

install:
  - mysql -e 'create database HydraCore;' &
  - composer install
  - sudo apt-get install ruby-dev build-essential nodejs
  - npm install -g less
  - gem install sass --pre
  - cd .tests
  - sudo sh before.sh

script: ../vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php --process-isolation --verbose --debug --colors --stop-on-failure --configuration phpunit.xml

after_script:
  - cd ..
  - rm -rf *